### ISSUE TITLE
Typo in documentation on deploying agent(monitoring section)

### ISSUE THREAD

**Issue by arbabnazar** [metis-data/metis-book#46]
There is a typo in at this page: https://docs.metisdata.io/Monitoring/the_metis_agent/Prerequisites_rds
Instead of `pg_stat_statements` there is `pg_stat_statement`

I think the relevant modification is at this line https://github.com/metis-data/metis-book/blob/dee702b1b72f25d30be0fb9f1863f241ffade2c5/docs/Monitoring/the_metis_agent/Prerequisites_rds.md?plain=1#L59

**Comment by oshrimy** [comment]
Fixed, Thanks @arbabnazar
